version: 2.1
orbs:
  node: circleci/node@4.7
  terraform: circleci/terraform@3.1.0
  azure-cli: circleci/azure-cli@1.2.2
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  docker-push:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$mydockerhub_user" --password-stdin
            docker build -t socka .
            docker tag socka rghdrizzle/socka
            docker push rghdrizzle/socka 
      - run:
          name: "Docker Logout"
          when: always
          command: docker logout
  terraform:
    docker:
      - image: rghdrizzle/az-tf-k8s
    steps:
    - checkout
    - run:
        command: az login --tenant "${AZURE_TENANT}"
    - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TF_API\"}" > $HOME/.terraformrc
    - terraform/init:
        path: ./terraform
    - terraform/plan:
        path: ./terraform
    - terraform/apply:
        path: ./terraform
    - run:
        command: kubectl get pods --kubeconfig $KUBE
    - run: 
        command: kubectl apply -k ./kubernetes --kubeconfig $KUBE
    - run:
        command: kubectl get svc --kubeconfig $KUBE
    - terraform/destroy:
        path: ./terraform







 

workflows:
  docker-pushing:
    jobs:
      - docker-push: 
          filters:
            tags:
              only: /^d.*/
            branches:
              ignore: main
      - terraform
         
            

        

  