version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$mydockerhub_user" --password-stdin
            docker build -t socka .
            docker tag socka rghdrizzle/socka
            docker push rghdrizzle/socka 
      - run:
          name: "Docker Logout"
          when: always
          command: docker logout
      
 

workflows:
  docker-pushing:
    jobs:
      - build: 
          filters:
            tags:
              only: /^d.1.*/
            

        

  