version: 2.1
orbs:
  node: circleci/node@4.7
  terraform: circleci/terraform@3.1.0
  azure-cli: circleci/azure-cli@1.2.2
jobs:
  docker-push:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$mydockerhub_user" --password-stdin
            docker build -t socka .
            docker tag socka rghdrizzle/socka
            docker push rghdrizzle/socka 
      - run:
          name: "Docker Logout"
          when: always
          command: docker logout
  terraform:
    docker:
      - image: zenika/terraform-azure-cli
    steps:
    - checkout
    - run:
        command: az login --tenant "${AZURE_TENANT}"
    - run:
        command: echo "yes"| terraform login | echo "$TF_API" 
    - terraform/init:
        path: ./terraform
    - terraform/plan:
        path: ./terraform
    - terraform/apply:
        path: ./terraform
    - run:
        command: kubectl get pods --kubeconfig kubeconfig-dev
    - run: 
        command: kubectl apply -k ./kubernetes --kubeconfig kubeconfig-dev
    - run:
        command: kubectl get svc --kubeconfig kubeconfig-dev







 

workflows:
  docker-pushing:
    jobs:
      - docker-push: 
          filters:
            tags:
              only: /^d.*/
            branches:
              ignore: main
      - terraform
         
            

        

  