version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$mydockerhub_user" --password-stdin
      
 

workflows:
  docker-pushing:
    jobs:
      - build
  