version: 2.1
orbs:
  node: circleci/node@4.7
  terraform: circleci/terraform@3.1.0
jobs:
  docker-push:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$mydockerhub_user" --password-stdin
            docker build -t socka .
            docker tag socka rghdrizzle/socka
            docker push rghdrizzle/socka 
      - run:
          name: "Docker Logout"
          when: always
          command: docker logout
  terraform:
    executor: terraform/default
    steps:
    - checkout
    - terraform/init:
        path: ./terraform
    - terraform/plan:
        path: ./terraform






 

workflows:
  docker-pushing:
    jobs:
      - docker-push: 
          filters:
            tags:
              only: /^d.*/
            branches:
              ignore: main
      - terraform
            

        

  