apiVersion: apps/v1
kind: Deployment
metadata:
  name: socka
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: socka
  template:
    metadata:
      labels:
        app: socka
    spec:
      containers:
      - name: socka
        image: rghdrizzle/socka:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password




     
       
