apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-socka
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306

        volumeMounts:
          - name: sql-pvc
            mountPath: /var/lib/mysql
      volumes:
        - name: sql-pvc
          persistentVolumeClaim:
            claimName: pvc-sql
     
        

       
